server:
  port: 8080

spring:
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

jwt:
  secret: B6E5061FADAD40CCAEBDD0F4B3EB3DEE3F4FCE86695FA0076BA9E0A894A53140