spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ab-project
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  quartz:
    job-store-type: memory